apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-chat
  namespace: firsteps-dev
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "ms-chat"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-set-headers: |
      Connection "upgrade"
      Upgrade "websocket"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://firstepscol.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"

spec:
  ingressClassName: public
  rules:
    - host: 
      http:
        paths:
          - path: /api/ms-chat
            pathType: Prefix
            backend:
              service:
                name: ms-chat
                port:
                  number: 8086
